spring:
  mail:
    host: smtp.domain
    protocol: smtp
    default-encoding: UTF-8
    password: your_password
    username: your_username
    port: 587
    properties:
      mail:
        debug: false
      stmp:
        socketFactory:
          class: javax.net.ssl.SSLSocketFactory